version: '2'
services:
    ui-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ui/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=90630690
        ports:
            - 5432:5432
